trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 2
    maxParallelTrials: 1
    hyperparameterMetricTag: val_auc
    params:
    - parameterName: batch-size
      type: INTEGER
      minValue: 100
      maxValue: 100
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: learning-rate
      type: DOUBLE
      minValue: 0.005
      maxValue: 0.005
      scaleType: UNIT_LOG_SCALE
