trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 3
    maxParallelTrials: 1
    hyperparameterMetricTag: val_auc
    params:
    - parameterName: learning-rate
      type: DOUBLE
      minValue: 0.0001
      maxValue: 0.01
      scaleType: UNIT_LOG_SCALE
